development:
  host: 127.0.0.1
  port: 27017
  database: passbook_development

production:
  host: 127.0.0.1
  port: 27017
  database: vdayu_production

test:
  host: 127.0.0.1
  port: 27017
  database: vdayu_test
